"""create rates

Revision ID: c6d723b5c6e5
Revises: 
Create Date: 2024-11-17 23:59:00.813708

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c6d723b5c6e5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tariffs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cargo_type", sa.String(), nullable=True),
        sa.Column("rate", sa.Float(), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tariffs_cargo_type"), "tariffs", ["cargo_type"], unique=False
    )
    op.create_index(
        op.f("ix_tariffs_effective_date"), "tariffs", ["effective_date"], unique=False
    )
    op.create_index(op.f("ix_tariffs_id"), "tariffs", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tariffs_id"), table_name="tariffs")
    op.drop_index(op.f("ix_tariffs_effective_date"), table_name="tariffs")
    op.drop_index(op.f("ix_tariffs_cargo_type"), table_name="tariffs")
    op.drop_table("tariffs")
    # ### end Alembic commands ###
